server:
  port: 8083

spring:
  application:
    name: parcel-service

  datasource:
    url: jdbc:postgresql://localhost:5432/parceldb
    username: postgres
    password: yourPassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka